// src/services/mockData.js

export const MOCK_CONTENT = [
  {
    id: '1',
    type: 'job',
    category: 'jobs',
    title: 'Senior React Developer needed - Remote',
    description: 'Looking for an experienced React developer to join our growing team. Must have 5+ years experience with React, TypeScript, and modern web technologies.',
    media: [
      { url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop', type: 'image', alt: 'Coding' }
    ],
    location: {
      city: 'New York',
      state: 'NY',
      coordinates: [40.71, -74.0],
    },
    price: { amount: 150000, currency: 'USD', priceType: 'yearly' },
    author: {
      id: 'author1',
      name: 'Tech Company',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tech',
      trustScore: 92,
      verified: true,
    },
    engagement: { views: 234, likes: 12, comments: 5, shares: 2, saves: 8 },
    tags: ['react', 'javascript', 'remote', 'fulltime'],
    isFeatured: true,
    isBoosted: false,
    isUrgent: false,
    status: 'active',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    type: 'housing',
    category: 'housing',
    title: '1 Bedroom Apartment in Manhattan',
    description: 'Newly renovated apartment with modern amenities. Near subway station. Landlord speaks Mongolian.',
    media: [
      { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop', type: 'image', alt: 'Apartment' }
    ],
    location: {
      city: 'New York',
      state: 'NY',
      coordinates: [40.71, -74.0],
    },
    price: { amount: 2500, currency: 'USD', priceType: 'monthly' },
    author: {
      id: 'author2',
      name: 'Landlord - Енхер',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=landlord',
      trustScore: 78,
      verified: false,
    },
    engagement: { views: 156, likes: 8, comments: 3, shares: 1, saves: 12 },
    tags: ['nyc', 'apartment', 'furnished', 'dogs_allowed'],
    isFeatured: false,
    isBoosted: true,
    isUrgent: false,
    status: 'active',
    amenities: ['Furnished', 'WiFi', 'Parking', 'Pets allowed'],
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    type: 'marketplace',
    category: 'marketplace',
    title: 'Used iPhone 13 - Excellent condition',
    description: 'iPhone 13 in excellent condition. Original box and accessories included. Price negotiable.',
    media: [
      { url: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=400&h=300&fit=crop', type: 'image', alt: 'iPhone' }
    ],
    location: {
      city: 'New York',
      state: 'NY',
      coordinates: [40.71, -74.0],
    },
    price: { amount: 750, currency: 'USD', priceType: 'fixed' },
    author: {
      id: 'author3',
      name: 'Munkhbat',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=munkhbat',
      trustScore: 85,
      verified: true,
    },
    engagement: { views: 89, likes: 5, comments: 2, shares: 0, saves: 4 },
    tags: ['iphone', 'electronics', 'used', 'excellent'],
    isFeatured: false,
    isBoosted: false,
    isUrgent: false,
    status: 'active',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    type: 'community_post',
    category: 'community',
    title: 'Mongolian Cultural Festival Coming to NYC!',
    description: 'Excited to announce the annual Mongolian Cultural Festival! Join us for traditional food, music, dance, and more. All community members welcome!',
    media: [
      { url: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=400&h=300&fit=crop', type: 'image', alt: 'Festival' }
    ],
    location: {
      city: 'New York',
      state: 'NY',
      coordinates: [40.71, -74.0],
    },
    author: {
      id: 'author4',
      name: 'Mongolian Community Center',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mcc',
      trustScore: 95,
      verified: true,
    },
    engagement: { views: 456, likes: 87, comments: 34, shares: 12, saves: 23 },
    tags: ['festival', 'cultural', 'community', 'mongolian'],
    isFeatured: true,
    isBoosted: false,
    isUrgent: false,
    status: 'active',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    type: 'event',
    category: 'events',
    title: 'Mongolian Language Meetup - Chicago',
    description: 'Monthly meetup for Mongolian speakers to practice language and connect with community. Location: Chicago Cultural Center',
    media: [
      { url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop', type: 'image', alt: 'Meetup' }
    ],
    location: {
      city: 'Chicago',
      state: 'IL',
      coordinates: [41.88, -87.63],
    },
    author: {
      id: 'author5',
      name: 'Language Club',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=langclub',
      trustScore: 88,
      verified: true,
    },
    engagement: { views: 234, likes: 45, comments: 12, shares: 8, saves: 19 },
    tags: ['language', 'mongolian', 'meetup', 'chicago'],
    isFeatured: false,
    isBoosted: false,
    isUrgent: false,
    status: 'active',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    type: 'service',
    category: 'services',
    title: 'Home Cleaning Service - Mongolian owned',
    description: 'Professional home cleaning with Mongolian-speaking team. Affordable rates, reliable service. Free estimates!',
    media: [
      { url: 'https://images.unsplash.com/photo-1527482797697-8795b1a826d0?w=400&h=300&fit=crop', type: 'image', alt: 'Cleaning' }
    ],
    location: {
      city: 'Los Angeles',
      state: 'CA',
      coordinates: [34.05, -118.24],
    },
    price: { amount: 150, currency: 'USD', priceType: 'range', range: [150, 500] },
    author: {
      id: 'author6',
      name: 'Clean Team LLC',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cleanteam',
      trustScore: 91,
      verified: true,
    },
    engagement: { views: 178, likes: 28, comments: 8, shares: 5, saves: 16 },
    tags: ['cleaning', 'service', 'affordable', 'mongolian'],
    isFeatured: false,
    isBoosted: false,
    isUrgent: false,
    status: 'active',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const MOCK_USER = {
  id: 'user123',
  name: 'Батаа',
  email: 'bataar@mongolsusa.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bataar',
  location: {
    city: 'New York',
    state: 'NY',
    coordinates: [40.71, -74.0],
  },
  trustScore: 85,
  verified: true,
  interests: ['jobs', 'community', 'housing'],
}
